### ISSUE TITLE
Clues receives infinite requests when a node is idle

### ISSUE THREAD

**Issue by alpegon** [grycap/clues#11]
How to reproduce the error:

* Launch a cluster with EC3 (using the ansible role recipes ('devel' branch of ec3 repo)):
```
./ec3 launch mycluster nfs slurm ubuntu14 -a auth.dat -u http://servproject.i3m.upv.es:8899 -y
```
* Launch a node inside the cluster:
```
clues poweron wn1
```
* When the node is idle launch a job:
```
- cat >> test.sh << EOF
  #!/bin/bash
  date > date.out
  /bin/hostname
  EOF
- sbatch test.sh
```

If you check the clues log you can see that the clues daemon is receiving infinite requests.
I've attached a complete clues log that has been generated due to this issue.
[clues2.txt](https://github.com/grycap/clues/files/585482/clues2.txt)

**Comment by micafer** [comment]
It was a problem of one of the ec3 recipes.
They have been fixed.
