### ISSUE TITLE
Slurm mixed state not recognized

### ISSUE THREAD

**Issue by davidramirezalvarez** [grycap/clues#14]
Hi. I used clues with Slurm. Clues put on and down nodes ok. But if some nodes are in "mixed" status. Clues status put "off" or "off error" status. Nodes idle work fin

The problem is that this mixed nodes have free resources, and clues try to power on another nodes.

Who I can insert the mixed status?

I see core count is correct

gpu17                          idle    enabled     02h32'23"      0,0.0           16,1.38141180625e+14
gpu18                      off (err    enabled     04h01'53"      8,0.0           16,1.38141180625e+14
gpu19                      off (err    enabled     03h31'23"      8,0.0           16,1.38141180625e+14

Thanks a lot

**Comment by dealfonso** [comment]
Hi @davidramirezalvarez 

this issue is solved in commit [solving issue #14](https://github.com/grycap/clues/commit/0f15260b1e32deba09461edd3d75a059918fa5e8)
