### ISSUE TITLE
Power On nodes

### ISSUE THREAD

**Issue by 0xPichi** [grycap/clues#16]
Buenos días, estoy realizando un TFG para la Universidad de Valladolid, y estoy teniendo problemas a la hora de que Clues encienda los nodos del cluster cuando son necesarios por los trabajos que se introducen en la cola.

**Comment by 0xPichi** [comment]
Buenos días, a la vista del email que he recibido les doy mas información acerca de mi caso, el sistema operativo que se esta utilizando para el cluster es Rocks Cluster el cual utiliza un sistema de colas de tipo SGE, en cuanto al WOL, es posible encender los nodos a través de la consola con el comando "ether-wakes -i ethX MAC". La cuestión es que tras configurar el plugin de WOL y lanzar trabajos al cluster cuando no hay nodos disponibles Clues no realiza el encendido de los nodos necesarios, revisando el log del mismo he podido ver que aparece un aviso del tipo "no hay peticiones de encendido para los nodos" me gustaría saber si necestitais algo más de información y espero que puedan ayudarme. Un saludo.

**Comment by 0xPichi** [comment]
Buenas tardes de nuevo, puesto que no obtengo una respuesta voy a dar algo más de información. estas son las lineas que aparecen cuando mando un nuevo trabajo a la cola de mi sistema pero no hay nodos disponibles para satisfacerla:

[SCHED];DEBUG;2017-02-28 18:42:14,723;1488303734.724;#6. request 2 cannot be satisfied, but there are no requests pending from powering on nodes, so let's free this request
   [SCHED];DEBUG;2017-02-28 18:42:14,723;1488303734.724;nodes allocated for 2: []

Espero que puedan ayudarme. Un slaudo.

**Comment by dealfonso** [comment]
Hola @0xPichi,

como no nos das mucho detalle de cómo has configurado CLUES en tu sistema, voy a intentar recopilar algunos de los posibles fallos que se me ocurren

1) la integración con SGE está un tanto abandonada en la versión 2 de CLUES, así que es posible que no esté bien instalado, ya no está documentado en la web. La versión 1 de CLUES sí que estaba bien testeada con SGE, así que pego un fragmento de la documentación de CLUES 1:

> 1.2 INSTALLING
> 
> The path in which CLUES system is installed will be called CLUES_PATH
> 
>   $ cd $CLUES_PATH/plugins
>   $ tar xvfz CLUES-SGE-X.XX.tar.gz
>   $ ln -s CLUES-SGE-X.XX sge
> 
> Configure CLUES to use this plug-in by including it in the configuration file, and
> adjust the config.py configuration file inside the SGE.
> 
> The $CLUES_PATH/plugins/sge/wrapper.py file must be set as the Job Submission
> Verifier of SGE at system level. Edit $SGE_ROOT/$SGE_CELL/common/sge_request file
> and add the following line:
> 
>   -jsv $CLUES_PATH/plugins/sge/wrapper.py
>  
> Finally you must set the SGE_JSV_TIMEOUT variable. Edit $SGE_ROOT/$SGE_CELL/common/settings.sh
> and set:
>  
>   export SGE_JSV_TIMEOUT=600 # Set the same time used in MAX_WAIT_JOB in the CLUES config file

Por favor, verifica que está todo instalado correctamente y que está funcionando. Me refiero a que deberías tener encendidos los nodos y ver que se están obteniendo correctamente los datos de monitorización. También que cuando envías un trabajo, se está llamando correctamente al script /plugins/sge/wrapper.py, de acuerdo a la versión de SGE que tengas instalada.

2) Por favor incluye la configuración del plugin SGE y del plugin WOL para vuestro sistema, para ver si vemos algo extraño.

3) Deberías verificar si con el comando

`clues poweron <nombre del nodo>`

se enciende el nodo, sin necesidad de esperar a que se encienda al enviar trabajos a las colas. En caso de que esto no vaya, probablemente sea por un fallo en la configuración del plugin de WOL o de WOL en sí mismo.

4) Deberías verificar si el fichero de maquinas para WOL está correctamente creado, utilizando los mismos nombres que se utilizan en SGE y con las MAC que van a aceptar las solicitudes de encendido de WOL.

Un saludo.

**Comment by 0xPichi** [comment]
Buenas tardes, tras un par de pruebas he conseguido solucionar hasta cierto punto la incidencia, uno de los problemas con los que me encuentro es lo que mencionas en el apartado de instalación pues el wrapper.py del sge que estoy utilizando es el que se encuentra en la carpeta de addons de clues. Una vez seguidos esos pasos pero utilizando el wrapper que comento, se ha solucionado el tema de las peticiones y los nodos se encienden correctamente cuando llega trabajo. Pero al parecer algo no funciona del todo como debería ya que al encenderse los nodos el servidor lanza esta excepción, la cual nose a que se debe.

> Exception happened during processing of request from ('127.0.0.1', 34598)
Traceback (most recent call last):
  File "/usr/lib64/python2.6/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.6/SocketServer.py", line 319, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.6/SocketServer.py", line 332, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.6/SocketServer.py", line 627, in __init__
    self.handle()
  File "/usr/lib64/python2.6/BaseHTTPServer.py", line 329, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.6/BaseHTTPServer.py", line 323, in handle_one_request
    method()
  File "/usr/lib64/python2.6/SimpleXMLRPCServer.py", line 490, in do_POST
    self.send_response(200)
  File "/usr/lib64/python2.6/BaseHTTPServer.py", line 384, in send_response
    self.send_header('Server', self.version_string())
  File "/usr/lib64/python2.6/BaseHTTPServer.py", line 390, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
  File "/usr/lib64/python2.6/socket.py", line 324, in write
    self.flush()
  File "/usr/lib64/python2.6/socket.py", line 303, in flush
    self._sock.sendall(buffer(data, write_offset, buffer_size))
error: [Errno 32] Broken pipe

De todas formas me gustaría saber como puedo obtener una versión de CLUES 1 en la que el SGE estuviera bien testado. Muchas gracias por su paciencia y atención.

Un saludo.

**Comment by dealfonso** [comment]
Hola @0xPichi 

lo siento, pero CLUES 1 ya no está disponible. Por otro lado, parece que los errores que te está dando son de python y ahi no podemos ayudarte. Quizá podrías probar a actualizar python a la 2.7.

Un saludo.
