### ISSUE TITLE
Minimum number of idle resources

### ISSUE THREAD

**Issue by iblanque** [grycap/clues#66]
Hi Carlos,

I wonder if CLUES can be extended to guarantee that a minimum number of machines are powered on. I want to guarantee that I can deal with a job with no delay, assuming the cost of always keeping one extra node up.

The rationale would be to keep always one idle node (provided that we do not reach the maximum). If a node becomes used for a given time, CLUES would power on a new node. For the powering off, the behaviour will be quite similar to the current one but ensuring that always one idle node is available. If there is more than one idle node for more than a given period, one node can be powered off.

This would be especially interesting when combined with EC3, due to the delay on the node configuration.

Thanks!

**Comment by dealfonso** [comment]
Hi,

sorry for the delay, but I was on holidays.

That feature is shipped with the standard distribution of CLUES. It includes the scheduler CLUES_Scheduler_PowOn_Free that implements it. It enables to have extra free nodes or extra free slots that will be kept in the system by CLUES (i.e. will not be powered off).

To activate it, you must enable the scheduler by including its class (i.e. clueslib.schedulers.CLUES_Scheduler_PowOn_Free) at the end of the schedulers (after the poweroff_idle). In the example configuration file, in the [SCHEDULER_CLASSES variable at line 118](https://github.com/grycap/clues/blob/29d57ceb744d0d003ef45ad69f6736b1661fb429/etc/clues2.cfg-full-example#L118). Then you can use the variables [EXTRA_SLOTS_FREE](https://github.com/grycap/clues/blob/29d57ceb744d0d003ef45ad69f6736b1661fb429/etc/clues2.cfg-full-example#L150) and [EXTRA_NODES_FREE](https://github.com/grycap/clues/blob/29d57ceb744d0d003ef45ad69f6736b1661fb429/etc/clues2.cfg-full-example#L153) to select the amount of idle slots (i.e. cores) or idle nodes that you want to have in the system.

I hope this helps.
