### ISSUE TITLE
Clues Reports - Error showing the areas of the deployed nodes

### ISSUE THREAD

**Issue by alpegon** [grycap/clues#80]
This error appears when printing the information about the state of the nodes.
In the image between 22:03 and 22:38 you can see the purple line but not the purple area that represents an idle node.
Also between 22:38 and 23:18 the area should show the use of 10 nodes, not 9. Also the idle area is missing one node.

![clues_error](https://user-images.githubusercontent.com/8695439/52205127-5fcc7e80-2876-11e9-9a7a-aa93c3fbb302.png)

If you check the cluesdata.js, the data is there, so it seems that it is an error from the graphs.

The data to reproduce the error can be found in this zip file. [reports.zip](https://github.com/grycap/clues/files/2827664/reports.zip)

Cheers

**Comment by dealfonso** [comment]
PR #92 solves this issue and others.
